import 'package:agreeo/shared/models/agreeo_models.dart';

const List<String> agreeoGenreOptions = <String>[
  'Action',
  'Thriller',
  'Comedy',
  'Drama',
  'Sci-Fi',
  'Fantasy',
  'Horror',
  'Romance',
  'Animation',
  'Crime',
  'Mystery',
  'Adventure',
  'Documentary',
  'Family',
  'War',
  'History',
];

const List<String> mockPopularWithFriendsIds = <String>[
  'dune-2',
  'spider-verse',
  'severance',
  'knives-out',
  'the-batman',
  'shogun',
];

String _poster(String seed) =>
    'https://placehold.co/600x900/111827/E5E7EB.png?text=$seed';

String _backdrop(String seed) =>
    'https://placehold.co/1280x720/0F172A/F8FAFC.png?text=$seed';

final List<Movie> mockMovieCatalog = <Movie>[
  Movie(
    id: 'arrival',
    tmdbId: 329865,
    title: 'Arrival',
    originalTitle: 'Arrival',
    overview:
        'A linguist is pulled into a global first-contact crisis and has to decode an alien language before panic outruns diplomacy.',
    posterUrl: _poster('Arrival'),
    backdropUrl: _backdrop('Arrival'),
    releaseYear: 2016,
    runtime: 116,
    genres: const <String>['Sci-Fi', 'Drama', 'Mystery'],
    director: 'Denis Villeneuve',
    cast: const <String>['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    rating: 7.9,
    mediaType: CatalogMediaType.movie,
    trailerUrl: 'https://www.youtube.com/results?search_query=Arrival+trailer',
  ),
  Movie(
    id: 'dune-2',
    tmdbId: 693134,
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    overview:
        'Paul Atreides joins the Fremen and steps closer to the destiny everyone fears, while the desert becomes a battleground of faith and survival.',
    posterUrl: _poster('Dune+Part+Two'),
    backdropUrl: _backdrop('Dune+Part+Two'),
    releaseYear: 2024,
    runtime: 166,
    genres: const <String>['Sci-Fi', 'Adventure', 'Drama'],
    director: 'Denis Villeneuve',
    cast: const <String>['Timothee Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    rating: 8.6,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Dune+Part+Two+trailer',
  ),
  Movie(
    id: 'spider-verse',
    tmdbId: 569094,
    title: 'Across the Spider-Verse',
    originalTitle: 'Spider-Man: Across the Spider-Verse',
    overview:
        'Miles Morales is flung across the multiverse and discovers that saving everyone may mean disagreeing with every Spider-Person in the room.',
    posterUrl: _poster('Spider-Verse'),
    backdropUrl: _backdrop('Spider-Verse'),
    releaseYear: 2023,
    runtime: 140,
    genres: const <String>['Animation', 'Action', 'Adventure'],
    director: 'Joaquim Dos Santos',
    cast: const <String>['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    rating: 8.7,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Across+the+Spider-Verse+trailer',
  ),
  Movie(
    id: 'past-lives',
    tmdbId: 666277,
    title: 'Past Lives',
    originalTitle: 'Past Lives',
    overview:
        'Two childhood friends reconnect decades later and have to sit with the life they imagined versus the one they built.',
    posterUrl: _poster('Past+Lives'),
    backdropUrl: _backdrop('Past+Lives'),
    releaseYear: 2023,
    runtime: 106,
    genres: const <String>['Drama', 'Romance'],
    director: 'Celine Song',
    cast: const <String>['Greta Lee', 'Teo Yoo', 'John Magaro'],
    rating: 8.1,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Past+Lives+trailer',
  ),
  Movie(
    id: 'knives-out',
    tmdbId: 546554,
    title: 'Knives Out',
    originalTitle: 'Knives Out',
    overview:
        'A flamboyant detective investigates a wealthy family after a suspicious death turns a birthday gathering into a maze of motives.',
    posterUrl: _poster('Knives+Out'),
    backdropUrl: _backdrop('Knives+Out'),
    releaseYear: 2019,
    runtime: 130,
    genres: const <String>['Mystery', 'Comedy', 'Crime'],
    director: 'Rian Johnson',
    cast: const <String>['Daniel Craig', 'Ana de Armas', 'Chris Evans'],
    rating: 7.9,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Knives+Out+trailer',
  ),
  Movie(
    id: 'the-batman',
    tmdbId: 414906,
    title: 'The Batman',
    originalTitle: 'The Batman',
    overview:
        'A younger Bruce Wayne hunts a serial killer through a rain-soaked Gotham where corruption feels older than the city itself.',
    posterUrl: _poster('The+Batman'),
    backdropUrl: _backdrop('The+Batman'),
    releaseYear: 2022,
    runtime: 176,
    genres: const <String>['Action', 'Crime', 'Drama'],
    director: 'Matt Reeves',
    cast: const <String>['Robert Pattinson', 'Zoe Kravitz', 'Paul Dano'],
    rating: 7.8,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=The+Batman+trailer',
  ),
  Movie(
    id: 'barbie',
    tmdbId: 346698,
    title: 'Barbie',
    originalTitle: 'Barbie',
    overview:
        'Barbie leaves Barbieland and discovers that the real world is more confusing, messier, and more revealing than perfect plastic ever prepared her for.',
    posterUrl: _poster('Barbie'),
    backdropUrl: _backdrop('Barbie'),
    releaseYear: 2023,
    runtime: 114,
    genres: const <String>['Comedy', 'Fantasy', 'Adventure'],
    director: 'Greta Gerwig',
    cast: const <String>['Margot Robbie', 'Ryan Gosling', 'America Ferrera'],
    rating: 7.2,
    mediaType: CatalogMediaType.movie,
    trailerUrl: 'https://www.youtube.com/results?search_query=Barbie+trailer',
  ),
  Movie(
    id: 'inside-out-2',
    tmdbId: 1022789,
    title: 'Inside Out 2',
    originalTitle: 'Inside Out 2',
    overview:
        'Riley grows older, and the emotional headquarters inside her mind suddenly has to make room for new feelings and a lot more uncertainty.',
    posterUrl: _poster('Inside+Out+2'),
    backdropUrl: _backdrop('Inside+Out+2'),
    releaseYear: 2024,
    runtime: 97,
    genres: const <String>['Animation', 'Comedy', 'Family'],
    director: 'Kelsey Mann',
    cast: const <String>['Amy Poehler', 'Maya Hawke', 'Ayo Edebiri'],
    rating: 7.9,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Inside+Out+2+trailer',
  ),
  Movie(
    id: 'palm-springs',
    tmdbId: 587792,
    title: 'Palm Springs',
    originalTitle: 'Palm Springs',
    overview:
        'Two wedding guests get stuck in a time loop and decide that if tomorrow never comes, they might as well become brutally honest.',
    posterUrl: _poster('Palm+Springs'),
    backdropUrl: _backdrop('Palm+Springs'),
    releaseYear: 2020,
    runtime: 90,
    genres: const <String>['Comedy', 'Romance', 'Sci-Fi'],
    director: 'Max Barbakow',
    cast: const <String>['Andy Samberg', 'Cristin Milioti', 'J.K. Simmons'],
    rating: 7.4,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Palm+Springs+trailer',
  ),
  Movie(
    id: 'get-out',
    tmdbId: 419430,
    title: 'Get Out',
    originalTitle: 'Get Out',
    overview:
        'A weekend visit with a girlfriend’s family turns into a quiet psychological trap where politeness feels more dangerous than open hostility.',
    posterUrl: _poster('Get+Out'),
    backdropUrl: _backdrop('Get+Out'),
    releaseYear: 2017,
    runtime: 104,
    genres: const <String>['Horror', 'Mystery', 'Thriller'],
    director: 'Jordan Peele',
    cast: const <String>['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'],
    rating: 7.8,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Get+Out+trailer',
  ),
  Movie(
    id: 'oppenheimer',
    tmdbId: 872585,
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    overview:
        'The story of J. Robert Oppenheimer unfolds as both a scientific sprint and a political reckoning with the cost of invention.',
    posterUrl: _poster('Oppenheimer'),
    backdropUrl: _backdrop('Oppenheimer'),
    releaseYear: 2023,
    runtime: 180,
    genres: const <String>['Drama', 'History', 'War'],
    director: 'Christopher Nolan',
    cast: const <String>['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'],
    rating: 8.4,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Oppenheimer+trailer',
  ),
  Movie(
    id: 'the-bear',
    tmdbId: 136315,
    title: 'The Bear',
    originalTitle: 'The Bear',
    overview:
        'A gifted young chef returns home to keep his family sandwich shop alive while every service threatens to become a pressure cooker.',
    posterUrl: _poster('The+Bear'),
    backdropUrl: _backdrop('The+Bear'),
    releaseYear: 2022,
    runtime: 35,
    genres: const <String>['Drama', 'Comedy'],
    director: 'Christopher Storer',
    cast: const <String>['Jeremy Allen White', 'Ayo Edebiri', 'Ebon Moss-Bachrach'],
    rating: 8.5,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=The+Bear+trailer',
  ),
  Movie(
    id: 'severance',
    tmdbId: 95396,
    title: 'Severance',
    originalTitle: 'Severance',
    overview:
        'Employees undergo a procedure that splits work memories from personal memories, creating a thriller about identity and corporate control.',
    posterUrl: _poster('Severance'),
    backdropUrl: _backdrop('Severance'),
    releaseYear: 2022,
    runtime: 50,
    genres: const <String>['Sci-Fi', 'Drama', 'Mystery'],
    director: 'Ben Stiller',
    cast: const <String>['Adam Scott', 'Britt Lower', 'John Turturro'],
    rating: 8.7,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Severance+trailer',
  ),
  Movie(
    id: 'shogun',
    tmdbId: 126308,
    title: 'Shogun',
    originalTitle: 'Shogun',
    overview:
        'In feudal Japan, power, loyalty, and survival collide as foreign arrival destabilizes a careful political balance.',
    posterUrl: _poster('Shogun'),
    backdropUrl: _backdrop('Shogun'),
    releaseYear: 2024,
    runtime: 58,
    genres: const <String>['Drama', 'History', 'War'],
    director: 'Frederick E.O. Toye',
    cast: const <String>['Hiroyuki Sanada', 'Anna Sawai', 'Cosmo Jarvis'],
    rating: 8.6,
    mediaType: CatalogMediaType.tv,
    trailerUrl: 'https://www.youtube.com/results?search_query=Shogun+trailer',
  ),
  Movie(
    id: 'the-last-of-us',
    tmdbId: 100088,
    title: 'The Last of Us',
    originalTitle: 'The Last of Us',
    overview:
        'A hardened survivor escorts a teenage girl across a ruined America where the human threat can be worse than the infected one.',
    posterUrl: _poster('The+Last+of+Us'),
    backdropUrl: _backdrop('The+Last+of+Us'),
    releaseYear: 2023,
    runtime: 56,
    genres: const <String>['Drama', 'Sci-Fi', 'Adventure'],
    director: 'Craig Mazin',
    cast: const <String>['Pedro Pascal', 'Bella Ramsey', 'Anna Torv'],
    rating: 8.8,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=The+Last+of+Us+trailer',
  ),
  Movie(
    id: 'only-murders',
    tmdbId: 107113,
    title: 'Only Murders in the Building',
    originalTitle: 'Only Murders in the Building',
    overview:
        'Three true-crime obsessives become amateur detectives when a death in their building gives them a real mystery to chase.',
    posterUrl: _poster('Only+Murders'),
    backdropUrl: _backdrop('Only+Murders'),
    releaseYear: 2021,
    runtime: 34,
    genres: const <String>['Comedy', 'Mystery', 'Crime'],
    director: 'John Hoffman',
    cast: const <String>['Steve Martin', 'Martin Short', 'Selena Gomez'],
    rating: 8.1,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Only+Murders+in+the+Building+trailer',
  ),
  Movie(
    id: 'andor',
    tmdbId: 83867,
    title: 'Andor',
    originalTitle: 'Andor',
    overview:
        'A grounded Star Wars thriller about ordinary people deciding that rebellion is worth the personal cost.',
    posterUrl: _poster('Andor'),
    backdropUrl: _backdrop('Andor'),
    releaseYear: 2022,
    runtime: 47,
    genres: const <String>['Sci-Fi', 'Adventure', 'Thriller'],
    director: 'Tony Gilroy',
    cast: const <String>['Diego Luna', 'Stellan Skarsgard', 'Genevieve O\'Reilly'],
    rating: 8.4,
    mediaType: CatalogMediaType.tv,
    trailerUrl: 'https://www.youtube.com/results?search_query=Andor+trailer',
  ),
  Movie(
    id: 'blue-eye-samurai',
    tmdbId: 122226,
    title: 'Blue Eye Samurai',
    originalTitle: 'Blue Eye Samurai',
    overview:
        'A master swordswoman moves through Edo-period Japan on a revenge quest that feels elegant, brutal, and deeply personal.',
    posterUrl: _poster('Blue+Eye+Samurai'),
    backdropUrl: _backdrop('Blue+Eye+Samurai'),
    releaseYear: 2023,
    runtime: 44,
    genres: const <String>['Animation', 'Action', 'Drama'],
    director: 'Jane Wu',
    cast: const <String>['Maya Erskine', 'Masi Oka', 'Brenda Song'],
    rating: 8.8,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Blue+Eye+Samurai+trailer',
  ),
  Movie(
    id: 'fallout',
    tmdbId: 106379,
    title: 'Fallout',
    originalTitle: 'Fallout',
    overview:
        'A vault dweller leaves underground safety and discovers a wasteland that is both absurd and terrifying in equal measure.',
    posterUrl: _poster('Fallout'),
    backdropUrl: _backdrop('Fallout'),
    releaseYear: 2024,
    runtime: 55,
    genres: const <String>['Sci-Fi', 'Comedy', 'Adventure'],
    director: 'Jonathan Nolan',
    cast: const <String>['Ella Purnell', 'Aaron Moten', 'Walton Goggins'],
    rating: 8.3,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Fallout+series+trailer',
  ),
  Movie(
    id: 'poor-things',
    tmdbId: 792307,
    title: 'Poor Things',
    originalTitle: 'Poor Things',
    overview:
        'Bella Baxter charges into the world with fearless curiosity, turning a strange rebirth story into a wild voyage of autonomy.',
    posterUrl: _poster('Poor+Things'),
    backdropUrl: _backdrop('Poor+Things'),
    releaseYear: 2023,
    runtime: 141,
    genres: const <String>['Comedy', 'Drama', 'Fantasy'],
    director: 'Yorgos Lanthimos',
    cast: const <String>['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe'],
    rating: 8.0,
    mediaType: CatalogMediaType.movie,
    trailerUrl:
        'https://www.youtube.com/results?search_query=Poor+Things+trailer',
  ),
  Movie(
    id: 'the-gentlemen',
    tmdbId: 158505,
    title: 'The Gentlemen',
    originalTitle: 'The Gentlemen',
    overview:
        'An aristocrat inherits his family estate and learns it sits on top of a criminal enterprise with more swagger than subtlety.',
    posterUrl: _poster('The+Gentlemen'),
    backdropUrl: _backdrop('The+Gentlemen'),
    releaseYear: 2024,
    runtime: 52,
    genres: const <String>['Crime', 'Comedy', 'Action'],
    director: 'Guy Ritchie',
    cast: const <String>['Theo James', 'Kaya Scodelario', 'Daniel Ings'],
    rating: 8.0,
    mediaType: CatalogMediaType.tv,
    trailerUrl:
        'https://www.youtube.com/results?search_query=The+Gentlemen+series+trailer',
  ),
];
